# Generated by Django 3.2.3 on 2021-05-26 20:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('ssh_key', models.CharField(blank=True, default=None, max_length=3000, null=True)),
                ('hostname', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='Inactive', max_length=255, null=True)),
                ('last_heartbeat', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DockerContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=1024)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('created', models.DateTimeField(max_length=255)),
                ('started', models.DateTimeField(max_length=255)),
                ('finished', models.DateTimeField(max_length=255)),
                ('args', models.CharField(max_length=255)),
                ('port_bindings', models.CharField(max_length=2000)),
                ('mounts', models.CharField(max_length=2000)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockerman_core.server')),
            ],
        ),
    ]
